 services:
  chat-server:
    build: ./server
    container_name: python-chat-server
    ports:
      - "12345:12345"
    volumes:
      - ./server/logs:/app/logs
    environment:
      - TZ=Asia/Seoul
    stdin_open: true
    tty: true
